### ISSUE TITLE
SD Card-Card Mount Failed

### ISSUE THREAD

**Issue by Sebastiangka** [FKainka/NodeESP_Firmware#2]
Hi @FKainka , i bought the Node-ESP and im programming it my self with Arduino IDE.
Right now i have problems with the SD Card. Even using SD_Test - Sketch from SD(esp32) i only get "Card Mount Failed"
I tried this codes(with delay(200) between Serial.begin(115200) and SD.begin): 

!SD.begin(SS)
!SD.begin(5)
!SD.begin()

Before using the SD-Cards (two differents Transcend microSDHC class10 4GB and an Intenso SDHC class 4 4GB)  i gave them the format FAT32 with the 16KB partition.
PS: As its ritten in your blog i choosed the Board ESP32 Dev Modul.

is there something that im missing so the SD Card cant be readed ?

**Comment by FKainka** [comment]
Hello, 
the new NodeESP-Firmware (released today) includes support for SD-Cards. You could test if the same error will be printed out via the serial monitor when you try your SD-Cards. If that is the case the Cards might be the problem. 

In the firmware I use the following lines to initiate the SD-Card-Library. It's probably the same you are using:

  if(!SD.begin()){
      Serial.println("Card Mount Failed");
      return false;
  }

**Comment by Sebastiangka** [comment]
Thanks for your answer and your update! It wasnt a code problem. I had to return the board because there was something wrong with the SD reader. I tested it with the new one and it works without problems, besides some warnings about libraries and so.
